package com.mycompany.cineclienteservidor;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FormAdmin extends javax.swing.JFrame {

    public class Globals {

        static ArrayList<Alimento> menuDelDia = new ArrayList<>();
        public static boolean alimentosGenerados = false;
    }

    public FormAdmin() {
        initComponents();

        mostrarInicioBtn.setVisible(false);
        idTxt.setEnabled(false);
        verAlimentos.setVisible(false);

//        for (Pago pago : FormCartelera.pagos) {
//            System.out.println(pago.mostrarPagos(FormCartelera.pagos));
//        }
        Pelicula pelicula = new Pelicula();
        DefaultTableModel modelo = pelicula.Mostrar();
        peliculasTb.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        duracionTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        generoTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        actoresTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        mostrarInicioBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tituloTxt = new javax.swing.JTextField();
        costoEntradaTxt = new javax.swing.JTextField();
        verPagosBtn = new javax.swing.JButton();
        alimentosBtn = new javax.swing.JButton();
        verAlimentos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        peliculasTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Panel de Administrador");

        jLabel6.setText("Id");

        jLabel3.setText("Titulo");

        jLabel4.setText("Duracion");

        jLabel5.setText("Genero");

        jLabel7.setText("Actores Principales");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        mostrarInicioBtn.setBackground(new java.awt.Color(0, 255, 51));
        mostrarInicioBtn.setForeground(new java.awt.Color(0, 0, 0));
        mostrarInicioBtn.setText("Mostrar Pantalla Principal");
        mostrarInicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInicioBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Costo de la Entrada");

        verPagosBtn.setBackground(new java.awt.Color(153, 255, 255));
        verPagosBtn.setForeground(new java.awt.Color(0, 0, 0));
        verPagosBtn.setText("Ver Transacciones");
        verPagosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPagosBtnActionPerformed(evt);
            }
        });

        alimentosBtn.setBackground(new java.awt.Color(255, 102, 204));
        alimentosBtn.setForeground(new java.awt.Color(0, 0, 0));
        alimentosBtn.setText("Generar/Mostrar Alimentos Especiales del Dia!");
        alimentosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentosBtnActionPerformed(evt);
            }
        });

        verAlimentos.setBackground(new java.awt.Color(255, 255, 153));
        verAlimentos.setForeground(new java.awt.Color(0, 0, 0));
        verAlimentos.setText("Ver Alimentos Especiales del Dia");
        verAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAlimentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duracionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(modificarBtn)
                        .addGap(238, 238, 238))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(actoresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(210, 210, 210)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verPagosBtn)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(279, 279, 279)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mostrarInicioBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(costoEntradaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alimentosBtn)
                                    .addComponent(verAlimentos))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alimentosBtn)
                            .addComponent(mostrarInicioBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verAlimentos)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(modificarBtn)
                    .addComponent(eliminarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoEntradaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actoresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verPagosBtn)))
        );

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lista de Peliculas");

        peliculasTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        peliculasTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peliculasTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(peliculasTb);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peliculasTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliculasTbMouseClicked
        int fila = peliculasTb.getSelectedRow();

        idTxt.setText(peliculasTb.getValueAt(fila, 0).toString());
        tituloTxt.setText(peliculasTb.getValueAt(fila, 1).toString());
        duracionTxt.setText(peliculasTb.getValueAt(fila, 2).toString());
        generoTxt.setText(peliculasTb.getValueAt(fila, 3).toString());
        actoresTxt.setText(peliculasTb.getValueAt(fila, 4).toString());
        costoEntradaTxt.setText(peliculasTb.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_peliculasTbMouseClicked

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed

        int duracion = Integer.parseInt(duracionTxt.getText());
        double costo = Double.parseDouble(costoEntradaTxt.getText());
        Pelicula pelicula = new Pelicula(0, tituloTxt.getText(), duracion, generoTxt.getText(), actoresTxt.getText(), costo);
        pelicula.Insertar();

        DefaultTableModel modelo = pelicula.Mostrar();
        peliculasTb.setModel(modelo);
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        int duracion = Integer.parseInt(duracionTxt.getText());
        double costo = Double.parseDouble(costoEntradaTxt.getText());
        int id = Integer.parseInt(idTxt.getText());
        Pelicula pelicula = new Pelicula(id, tituloTxt.getText(), duracion, generoTxt.getText(), actoresTxt.getText(), costo);
        pelicula.Modificar();

        DefaultTableModel modelo = pelicula.Mostrar();
        peliculasTb.setModel(modelo);
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        int duracion = Integer.parseInt(duracionTxt.getText());
        double costo = Double.parseDouble(costoEntradaTxt.getText());
        int id = Integer.parseInt(idTxt.getText());
        Pelicula pelicula = new Pelicula(id, tituloTxt.getText(), duracion, generoTxt.getText(), actoresTxt.getText(), costo);
        pelicula.Eliminar();

        DefaultTableModel modelo = pelicula.Mostrar();
        peliculasTb.setModel(modelo);
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void mostrarInicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInicioBtnActionPerformed

        FormInicio inicio = new FormInicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_mostrarInicioBtnActionPerformed

    private void verPagosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPagosBtnActionPerformed
        FormPagos transacciones = new FormPagos();
        transacciones.setVisible(true);
        transacciones.setDefaultCloseOperation(FormPagos.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_verPagosBtnActionPerformed

    private void alimentosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentosBtnActionPerformed
        if (!Globals.alimentosGenerados) {
            Globals.alimentosGenerados = true;
         
            ArrayList<Alimento> menu = Alimento.generarMenu();
            Hilo hilo = new Hilo();
            int num1 = (int) (Math.random() * 9) + 1;
            int num2 = (int) (Math.random() * 9) + 1;
            while (num1 == num2) {
                num2 = (int) (Math.random() * 9) + 1;
            }
            int num3 = (int) (Math.random() * 9) + 1;
            while (num1 == num3 || num2 == num3) {
                num3 = (int) (Math.random() * 9) + 1;
            }

            hilo.setAlimento(menu.get(num1 - 1));
            hilo.run();
            Globals.menuDelDia.add(hilo.getAlimento());
            hilo.setAlimento(menu.get(num2 - 1));
            hilo.run();
            Globals.menuDelDia.add(hilo.getAlimento());
            hilo.setAlimento(menu.get(num3 - 1));
            hilo.run();
            Globals.menuDelDia.add(hilo.getAlimento());

            verAlimentos.setVisible(true);

        } else if (Globals.alimentosGenerados && !verAlimentos.isVisible()) {
            verAlimentos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Alimentos ya fueron generados", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_alimentosBtnActionPerformed

    private void verAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAlimentosActionPerformed
        String msg = "";
        for (Alimento alimento : Globals.menuDelDia) {
            msg += alimento.getNombre() + "--" + alimento.bebidaIncluida() + "--" + alimento.getPrecio() + "\n";
        }
        JOptionPane.showMessageDialog(null, msg, "ALIMENTOS DEL DIA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_verAlimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actoresTxt;
    private javax.swing.JButton alimentosBtn;
    private javax.swing.JTextField costoEntradaTxt;
    private javax.swing.JTextField duracionTxt;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JTextField generoTxt;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JButton mostrarInicioBtn;
    private javax.swing.JTable peliculasTb;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JButton verAlimentos;
    private javax.swing.JButton verPagosBtn;
    // End of variables declaration//GEN-END:variables
}
